<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body style="font-family:'arial',verdana; box-sizing:border-box !important; -moz-box-sizing: border-box !important;	-webkit-box-sizing: border-box !important;	-o-box-sizing: border-box !important;">
	<table id="wrapper" width="600px" cellpadding="0"  style="margin:0; padding:0; position:relative; font-family:Arial,Verdana,sans-serif">
		<tr align="center"><td>
			<!-- Start of Header -->
			<table id="header" width="100%" height="148px" style="margin-bottom: 40px; min-width:510px; height:148px;overflow: hidden; box-shadow: 0 2px 5px #CCC;">
				<tr style="background-image:url('http://eldercare.starfi.sh/Project/Design/1_Website/Applications/Seeker/images/Eldercare-email-template-banner.png'); background-repeat:no-repeat;" width="600" height="100%">
					<td style="background-image:url('http://eldercare.starfi.sh/Project/Design/1_Website/Applications/Seeker/images/Eldercare-email-template-logo.png'); background-repeat:no-repeat;" width="200" height="100%">
						<span style="text-align:center;color:#FFFFFF;position: absolute;top: 105px;left: 43px;font-size:9px;">Visit our website:<br/><a style="color:#FFFFFF;" href="http://www.datavault.starfi.sh/">www.lookingforeldercare.com</a></span>
					</td>
				</tr>
				
			</table>
		<table id="content" style="min-width:510px;width:90%;color:#333333;margin:0 auto;">
			<tr><td style="color:#29ABE2;margin-bottom: 30px;">
				<h2 style="font-size:17px;">Your information is being reviewed by our team.  You will receive an email letting you know when you will start receiving referrals and leads.</h2>
			</td></tr>
			<tr>
				<td><img style="float:left" src="http://eldercare.starfi.sh/Project/Design/1_Website/Applications/Seeker/images/Eldercare-email-template-icon2.png"/><h3 style="font-size:15px;padding: 8px;margin:0 0 0 25px;">We would like to introduce you to:</h3></td>
			</tr>
			<tr><td>
		
				<table width="80%" style="font-size:13px;margin-bottom:50px;">
					<tr><td style="padding: 8px 20px;background-color:#E6E6E6;min-width:155px;">Username:</td><td style="padding: 8px 20px;background-color:#F2F2F2;min-width:355px;font-weight:bold;"><?php echo $_POST['email']?></td></tr>
					<tr><td style="padding: 8px 20px;background-color:#E6E6E6;min-width:155px;">Password:</td><td style="padding: 8px 20px;background-color:#F2F2F2;min-width:355px;font-weight:bold;"><?php echo  $_POST['password'] ?></td></tr>
				</table>
			</td></tr>
			<tr><td style="font-size:13px;font-weight:bold;">
				<p>Thank you for using Looking for ElderCare<sup class="fs-xxs">TM</sup>.</p><br/>
			
				<p>Wishing you the best success,</p>
				<p>Looking for ElderCare<sup class="fs-xxs">TM</sup> Team</p>
			</td></tr>
		</table>
		<table id="footer" style="background-color:#28A2D6;color:#FFFFFF !important;font-size:10px;width:100%;min-width:510px;margin-top:80px;padding: 15px 25px;text-align:center;">
			<tr><td>Copyright &copy; 2012 Looking for ElderCare<sup class="fs-xxs">TM</sup>, Inc. All rights reserved. We are paid by our participating communities and providers, therefore this service is offered at no charge to families. Lookingforeldercare.com complies with the Can-Spam Act of 2003.</tr></td>
		</table>
		</td></tr>
	</table>
</body>
</html>