INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (1, 'Activity Director', 1);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (2, 'Beautician/ Barber', 1);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (3, 'Billiard Room', 1);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (4, 'Clubhouse/ Meeting Room', 1);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (5, 'Computer/ Internet', 1);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (6, 'Concierge', 1);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (7, 'Family Visiting Area', 1);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (8, 'Fitness Center/ Gym', 1);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (9, 'Garden', 1);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (10, 'Guest Dining', 1);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (11, 'Guest Lodging', 1);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (12, 'Housekeeping', 1);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (13, 'Laundry Room', 1);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (14, 'Library', 1);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (15, 'Maintenance Director', 1);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (16, 'Parking', 1);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (17, 'Sauna/Whirlpool', 1);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (18, 'Swimming Pool', 1);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (19, 'TV/ Media Room', 1);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (20, 'Guest Lodging', 1);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (21, 'Housekeeping', 1);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (22, 'Laundry Room', 1);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (23, 'Library', 1);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (24, 'Maintenance Director', 1);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (25, 'Parking', 1);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (26, 'Sauna/Whirlpool', 1);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (27, 'Swimming Pool', 1);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (28, 'TV/ Media Room', 1);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (29, 'Air Conditioning', 2);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (30, 'Cable/Satellite Hookup', 2);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (31, 'Climate Control Thermostat', 2);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (32, 'Full Kitchen', 2);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (33, 'Microwave', 2);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (34, 'Private Courtyard or Balcony', 2);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (35, 'Private Telephone Lines', 2);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (36, 'Walk in Shower', 2);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (37, 'Washer/Dryer Hookup', 2);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (38, 'Wheel-In Shower', 2);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (39, 'Wheelchair Accessible', 2);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (40, '24hr Controlled Access', 3);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (41, '24hr Up and Awake Staff', 3);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (42, 'Fire Sprinkler System', 3);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (43, 'Gated Community', 3);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (44, 'In-Room Call System', 3);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (45, 'Security Staff on Premises', 3);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (46, 'Wander Guard', 3);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (47, 'Guest Parking', 4);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (48, 'Resident Parking', 4);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (49, 'Transportation Provided By Facility', 4);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (50, 'Buffet Style', 5);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (51, 'Restaurant Style', 5);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (52, 'Room Service As Needed', 5);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (53, 'Dogs', 6);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (54, 'Cats', 6);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (55, 'Assistance', 7);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (56, 'Full Lift', 7);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (57, 'Stand By Assistance', 7);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (58, 'Walker', 7);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (59, 'Wheelchair', 7);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (60, 'Activities of Daily Living', 8);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (61, 'Ambulation Help', 8);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (62, 'Catheter Management', 8);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (63, 'Colostomy Care', 8);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (64, 'Feeding', 8);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (65, 'Feeding', 8);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (66, 'Foot Care', 8);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (67, 'Grooming', 8);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (68, 'Medication Management', 8);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (69, 'Toileting', 8);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (70, 'Alzheimer\'s', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (71, 'Arthritis', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (72, 'Asthma', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (73, 'Bariatric Needs', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (74, 'Breathing Support', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (75, 'Broken Bones', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (76, 'Cancer', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (77, 'Dementia', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (78, 'Depression', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (79, 'Diabetes: Diet Controlled', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (80, 'Diabetes: Oral Medication', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (81, 'Diabetes: Staff Injection', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (82, 'Emphysema/Lung Disease (COPD)', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (83, 'Heart Disease/ Heart Failure', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (84, 'Incontinence', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (85, 'Memory loss', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (86, 'Monitored Food Intake', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (87, 'Multiple Sclerosis', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (88, 'Osteoporosis', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (89, 'Parkinson\'s', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (90, 'Psychiatric Conditions', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (91, 'Stroke', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (92, 'Tendency To Fall', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (93, 'Traumatic Brain Injury', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (94, 'Wanderer', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (95, 'Wound Treatment', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (96, 'Diabetes: Oral Medication', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (97, 'Diabetes: Staff Injection', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (98, 'Emphysema/Lung Disease (COPD)', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (99, 'Heart Disease/ Heart Failure', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (100, 'Incontinence', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (101, 'Memory loss', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (102, 'Monitored Food Intake', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (103, 'Multiple Sclerosis', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (104, 'Osteoporosis', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (105, 'Parkinson\'s', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (106, 'Psychiatric Conditions', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (107, 'Stroke', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (108, 'Tendency To Fall', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (109, 'Traumatic Brain Injury', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (110, 'Wanderer', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (111, 'Wound Treatment', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (112, 'Parkinson’s', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (113, 'Psychiatric Conditions', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (114, 'Stroke', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (115, 'Tendency To Fall', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (116, 'Traumatic Brain Injury', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (117, 'Wanderer', 9);
INSERT INTO amenities (`amenity_id`, `amenity`, `amenities_category_id`) VALUES (118, 'Wound Treatment', 9);