<!-- outer wrapper start-->
<div id="outer_wrapper" class="clearfix">

	<!-- content column start -->
	<div id="contentColumn">
		<div id="applicationContainer">
			<div id="applicationContent" class="pAl pLs fleft">
				%%APPLICATION_CONTENT%%
			</div>
			<div id="applicationSideBar" class="pAl pLs fright">
				%%APPLICATION_SIDEBAR%%
			</div>
		</div>
	</div>
	<!-- content column end -->
	
</div>
<!-- outer wrapper end-->

<div class="transparent_background hide"></div>