<div id="<?=routes::getInstance()->getCurrentTopLevelPageID();?>_content_wrapper">
	<div id="header_banner">
		<div class="semi_transparent"></div>
	</div>
	<div id="page_content" class="clearfix">
		<a href = "/" class="back sprite">Back to Home</a>
		<div class="pHxxl pVxl clearfix">
			<h1 class="helvetica77 fcBlue mVl">About Looking For ElderCare<sup class="fs-xxs">TM</sup></h1>
			<h3 class="gotham_bold">What sets us apart from other Assisted Living information sites?</h3>
			<img class="fright" alt="assisted living" src="/Project/Design/1_Website/Pages/primary/about/images/Eldercare_About_branding.png"/>
			<p class="mTl gotham_book">
				We here at Looking for ElderCare<sup class="fs-xxs">TM</sup> strive to provide you with the <strong class="gotham_bold">most up to date information about Assisted Living Homes and care options.</strong>  We believe in establishing relationships.  We do this by connecting you and your loved ones with the right health care provider.  What sets us apart is the whole package.
				<br/><br/>
				When you  use Looking for ElderCare<sup class="fs-xxs">TM</sup> to help connect with potential health care providers, you will be working with people that believe in education, establishing honest relationships, sincerity, quality of character, and the belief that we truly are the number one site for you and your loved ones search for care.   Thank you for visiting Looking For ElderCare<sup class="fs-xxs">TM</sup>
			</p>
			<h3 class="gotham_bold mTxxl">How our site works</h3>
			<p class="gotham_book">
				We understand that each of our clients is unique and has special care needs.  We are here to offer our guidance and support in finding the right care for your loved one through these simple steps.
			</p>
			<img class="mBxl" alt="how eldercare site works" src="/Project/Design/1_Website/Pages/primary/about/images/Eldercare_About.png" />
			<p id="note" class=" fleft gotham_bold">We aim to make sure the options for your loved one are clearly explained so that you may make an informed and confident choice.</p>
			<a href="/" class="fright sprite get_started">Back to home</a>
		</div>
	</div>
</div>