<!-- outer wrapper start-->
<div id="outer_wrapper" class="clearfix">
	<!-- left hand nav -->
	<div id="leftColumn" class="fleft"> 
	%%APPLICATION_LEFT_COLUMN%%
	<!-- left hand nav end -->
	</div> 
	<!-- content column start -->
	<div id="contentColumn" class="fright">
		<div id="applicationContainer">
			<div id="applicationContent" class="pAl pLs pRxl fleft posRel">
				%%PROFILE%%
			</div>
		</div>
	</div>
	<!-- content column end -->
</div>
<!-- outer wrapper end-->
<div class="transparent_background hide"></div>