<div id="header">
	<div class="clearfix">
		<div id='logo-holder' class="fleft pTxs">
			<h1><a href='/'><img alt="Looking for ELDERCARE? " title="" src="/Project/Design/1_Website/Panels/header/images/logo.png"></a></h1>	
		</div>
		<div id='navigation'>
			<span class="fright sprite account" title="HEALTH CARE PROVIDER ACCOUNT">
				<?=accountPanel::showAccountPanel()?>
			</span>
			<?= navigation::displayNavigationForPages('primary','browse,zipcode_search,seeker,health_care_provider'); ?>
			
		</div>
	</div>
</div>