<table class="new_leads tablesorter active">
	<thead>
		<tr>
			<th>Date and Time</th>
			<th>Contact Name</th>
			<th>City, State</th>
			<th>Preferred Facility</th>
			<th>Relationship to Seeker</th>
			<th> </th>
		</tr>
	</thead>
	<tbody>%%NEW_LEADS%%</tbody>
</table>

<table class="new_placements tablesorter">
	<thead>
		<tr>
			<th>Date and Time</th>
			<th>Contact Name</th>
			<th>City, State</th>
			<th>Preferred Facility</th>
			<th>Relationship to Seeker</th>
			<th> </th>
		</tr>
	</thead>
	<tbody>%%NEW_PLACEMENTS%%</tbody>
</table>

<table class="calendar_alerts tablesorter">
	<thead>
		<tr>
			<th>Date and Time</th>
			<th>For</th>
			<th>From</th>
			<th>Action</th>
			<th>View Profile</th>
		</tr>
	</thead>
	<tbody>%%CALENDAR_ALERTS%%</tbody>
</table>

<table class="new_hcp tablesorter">
	<thead>
		<tr>
			<th>Name</th>
			<th>Joined Date</th>
			<th>City, State</th>
			<th>Zip Code</th>
			<th>Pricing</th>
			<th>Status</th>
		</tr>
	</thead>
	<tbody>%%NEW_HCP%%</tbody>
</table>

<table class="new tablesorter">
	<thead>
		<tr>
			<th>Date/Time</th>
			<th>Contact Name</th>
			<th>Chosen Facility</th>
			<th>Consultant</th>
			<th>Invoice No.</th>
			<th>Status</th>
		</tr>
	</thead>
	<tbody>%%NEW_PLACEMENTS_AND_PAYMENT_STATUS%%</tbody>
</table>

