<div id="login_content_wrapper">

	<div id="header_banner">
		<div class="semi_transparent"></div>
	</div>
	
	<div id="page_content" class="clearfix">
		<a class="back sprite mBxl" href="/"></a>
		<h1 class="pTl helvetica77">Reset <span class="fcBlue">Password</span></h1>
		<span class="gotham_bold fs-m">Please enter your new password.</span>
		
		<div class="clearfix mTl mBxxl gotham_bold" id="resetPasswordField">
			<form id="resetPassword" method='post'> 
				 <p class="posRel">New Password : <br/><input class="mTm" type='password' name='password' /></p>
				 <p class="posRel">Retype New Password : <br/><input class="mTm" type='password' name='verify_password' /></p>
				 <input class=" sprite submitBtn fright" type='submit' name='resetPassword' />
			</form>
		</div>
		<a class="back sprite mBxl" href="/"></a>
	</div>
</div>


<br /> <br /> <br /> <br /> <br />