<? 
	$url	= request::getInstance()->getParametersArray();
	$seeker = $this->_get('seeker');
	$lead	= $this->_get('lead');
	
	$application_id	= routes::getInstance()->getCurrentTopLevelURLName();
	$controller_id	= applicationsRoutes::getInstance()->getCurrentControllerID();
	
	$controller_id = $application_id == 'your_leads'? '':'/'.$controller_id;
?>
<?php if($seeker->__get('name') !== null):?>
<!-- SEEKER INFO --------------------------------------------------------------------------------->
<div class="overflowAuto">
	<div class="profile_info fleft">
		<h3 class="mBm"><?=$seeker->__get('name')?><?=(int)$lead->__get('urgent') == 1 ? ' (Urgent)' : ''?></h3>
		
		<input type="hidden" name="seeker_id" value="<?=$seeker->__get('seeker_id')?>">
		<table class="fleft fs-s">
			<tr>
				<td>Date of Inquiry:</td>
				<td><?=date('M-d-y h:i:s A',strtotime($seeker->__get('date_of_inquiry')))?></td>
			</tr>
			<tr>
				<td>Telephone:</td>
				<td><?=$seeker->__get('telephone')?></td>
			</tr>
			<tr>
				<td>Email:</td>
				<td><?=$seeker->__get('email')?></td>
			</tr>
			<tr>
				<td>House for:</td>
				<td><?=$seeker->__get('relationship_to_patient')?></td>
			</tr>
			<tr>
				<td>Area:</td>
				<td><?=$seeker->__get('city').', '.$seeker->__get('state')?></td>
			</tr>
			<tr>
				<td>ZIP Code:</td>
				<td><?=$seeker->__get('zipcode')?></td>
			</tr>
		</table>
	</div>
	
	<div class="fs-s fright">
		<a class="deleteBtn" href="/<?=$application_id.$controller_id?>/delete/<?=$seeker->__get('seeker_id')?>"></a>
		
		<?$status	= $lead->__get('status')=='closed'?'open':'close';?>
		<?$class	= $lead->__get('status')=='closed'?'reopenBtn':'closeBtn'?>
		<a class="<?=$class?>" href="/<?=$application_id.$controller_id?>/<?=$status?>/<?=$seeker->__get('seeker_id')?>"></a>
		
		<?$urgent	= $lead->__get('urgent')=='1'?'remove_urgent':'urgent';?>
		<?$class	= $lead->__get('urgent')=='1'?'noturgentBtn':'urgentBtn'?>
		<a class="<?=$class?>" href="/<?=$application_id.$controller_id?>/<?=$urgent?>/<?=$seeker->__get('seeker_id')?>"></a>
		<span class="sprite addAlarmBtn"></span>
	</div>
</div>

<div class="posRel division"></div>

<div id="table_tabs" class="clearfix">
	<div class="fleft active" id="potential_hcps">
		<div>New Placements and Payment Status</div>
		<div class="bottom_corner_curve"></div>
	</div>
	<div class="fleft" id="calendar_events">
		<div>Calendar</div>
		<div class="bottom_corner_curve"></div>
	</div>
	<a class="addHCPBtn fright" href="/hcps/recommend_seeker/<?=$seeker->__get('seeker_id')?>"></a>
</div>
<div class="table_container">

	<!-- POTENTIAL HCPS ----------------------------------------------------------------------------->
	<table class="active potential_hcps tablesorter">
		<thead>
			<tr>
				<th>Likes</th>
				<th>Health Care Provider</th>
				<th>Details</th>
				<th>Contact Made</th>
				<th>Info Sent/Visited</th>
				<th>Placement</th>
			</tr>
		</thead>
		<tbody>%%POTENTIAL_HCPS%%</tbody>
	</table>
	
	%%CALENDAR%%
						
</div>

<div class="posRel division"></div>

%%CONVERSATION_HISTORY%%

<!-- EDIT SEEKER INFO ----------------------------------------------------------------------------->
	

<div class="popupDialog addAlarm">%%ADD_ALARM_FORM%%</div>

<?php endif;?>	