<div id="<?=routes::getInstance()->getCurrentTopLevelPageID();?>_content_wrapper">
	<div id="header_banner">
		<div class="semi_transparent"></div>
	</div>
	<div id="page_content">
		<div id="register_container">	
			<form method="post">
					<h5>Register</h5>
				<div id="form_fields">
					<div>Email<input type="text" name="email"></div>
					<div>Password<input type="password" name="password"></div>
					<div>Confirm Password:<input type="password" name="password"></div>
				</div>	
				<input type="submit" name="login" value="Proceed To Delivery">
			</form>
		</div>
	</div>
</div>