<link rel="stylesheet" href="/Project/Design/2_Enterprise/Applications/_Common/css/common.css" type="text/css" media="screen" />
<script src="/Project/Design/2_Enterprise/Applications/_Common/templates/inpage_javascript.js"></script>
<script type="text/javascript" src="/Project/Design/2_Enterprise/Main_Layout/scripts/htmlbox.colors.js"></script>
<script type="text/javascript" src="/Project/Design/2_Enterprise/Main_Layout/scripts/htmlbox.styles.js"></script>
<script type="text/javascript" src="/Project/Design/2_Enterprise/Main_Layout/scripts/htmlbox.syntax.js"></script>
<script type="text/javascript" src="/Project/Design/2_Enterprise/Main_Layout/scripts/xhtml.js"></script>
<script type="text/javascript" src="/Project/Design/2_Enterprise/Main_Layout/scripts/htmlbox.full.js"></script>