<!-- outer wrapper start-->
<div id="resetPasswordContainer" class="clearfix mAuto">
	<div id="form_fields">
		<h1>Reset Password</h1>
		<form method='post' action='/recovery/forgot-password/requestPassword'> 
			<table class="mVxxl align_c">
				<tbody>
					<tr><td><span class="fwB pTxs fs-m">Please enter your e-mail address</span></td></tr>
					<tr><td><input class=" fs-xs fc_starfish_gray5" type="text" name="email" autocomplete="off"></td></tr>
					<tr><td><input class="sprite2" type='submit' name='resetPassword' /></td></tr>
					<tr class="mVxxl"><td><span id="emailConfirmation" class="fs-s hide">An Email has been sent to you containing your new password.</span></td></tr>
				</tbody>
			</table>
		</form>
	</div>	
</div>
<!-- outer  wrapper end-->