<!-- outer wrapper start-->
<div id="login_container">	
	<form method="post">
		<h5>Member Login</h5>
		<div id="form_fields">
			<div>Email <input type="text" name="username"></div>
			<div>Password <input type="password" name="password"></div>
		</div>	
		<input type="submit" name="login" value="login">
	</form>
</div>
<br><br><br>
<div id="register_container">	
	
		<h5>Register</h5>
		<a href="/user/register">CLICK HERE TO REGISTER</a>
</div>
<!-- outer  wrapper end-->