<div class="fleft" id="leftColumn">
	<div class="pAl" id="heading">
		<h3>SEARCH HCPS</h3>
		
	</div>
	<div class="clearfix mLl" id="sideNavigation">
		<form method="POST" action="/hcps/search/results">
			<div>
				<label>Name</label>
				<input type="text" name="name" id="hcp_name_search">
			</div>
			<div>
				<label>State</label>
				<input type="text" name="state" id="hcp_state_search">
			</div>
			<div>
				<label>Zip Code</label>
				<input type="text" name="zipcode" id="hcp_zipcode_search">
			</div>
		</form>
	</div>
</div>
<!-- left hand nav end -->