	<div class="popupDialog">
		<span class="close gotham_book pointer">x</span>
		<p class="gotham_bold fwB">Congratulations, your profile has been approved by  Looking for ElderCare<sup class="fs-xxs">TM</sup></p>
		<span class="gotham_book fleft">Remember to read you <a href="/privacy_policy" target="_blank">terms of agreement</a> and contract on or rates..</span>
		<form  method='post' class='fleft'> 
			<span class="gotham_bold" id="proceedNow"><input type='button' name='proceed' id='proceedApproved' value='Proceed Now' />Click here to Proceed</span>
		</form>
	</div>
