<!-- outer wrapper start-->
<div id="content_wrapper" >
	<?$zip = $this->_get('zipcode'); ?>
	<div><a href="">View Online</a></div>
	<div id="leftside_navigation" class="fleft"> %%LEFTSIDE_NAVIGATION%%</div>
	<!-- <form method="post" action="/account/profile"> -->
		<div id="tab_content" >%%TAB_CONTENT%%</div>
		<input type="submit" name="profile" value="Save"> <input type="button" value="Publish">
	<!-- </form> -->
</div>
<!-- outer  wrapper end-->