	<div class="popupDialog">
		<span class="close gotham_book pointer">x</span>
		<p class="gotham_bold fwB">Thank you for joining Looking for ElderCare<sup class="fs-xxs">TM</sup></p>
		<span class="gotham_book fleft">Your account has been suspended. Please contact your...</span>
		<!-- <form  method='post' class="fleft"> 
			<span class="gotham_bold"><input type='submit' name='proceed' id='proceed' value='Proceed Now' />Proceed Now</span>
		</form> -->
	</div>
