<div><!-- DIV holds orange band -->
	<div>
		<h3 class="fleft pRl"><span class="sprite assisted_living" title="Find Assisted Living Now"></span></h3>
		<form method = "GET" action = "/health-care-search" id="searchForm">
			<label class="fleft clearfix posRel"><span class="gotham_bold fs-m">Enter Zip Code</span><br/>
			<input type = "text" name = "query" placeholder="Zip Code" onkeypress="return isNumberKey(event)" autocomplete="off" tabindex="1" />
			<input type = "hidden" name = "zipcode_id"></label>
			
			<div id = "suggestion_list" class="clearfix"></div>
			
			<label class="fleft clearfix"><span class="gotham_bold fs-m">Housing Type</span><br/>
			<select name = "housing_type" tabindex="2">
				<option value = "">I'm looking for</option>
				<option value = "Assisted Living">Assisted Living</option>
				<option value = "Memory Care">Memory Care</option>
				<option value = "Residential Care">Residential Care</option>
				<option value = "Home Care">Home Care</option>
			</select> 
			</label>
			<input class="sprite search fright" type = "submit" value = " " name = "get_started" tabindex="3">
		</form>
	</div>
</div>