<div class="popupDialog  hide popUp_delete unassignedLeads">
    <span class="deleteText fc_starfish_gray8 fwB popupText"></span>
    <div id="button_container">
         <span id='closePopup' class="sprite pointer mTs" title="Ok"></span>
    </div>
</div>

<table class="active new_leads tablesorter">
	<thead>
		<tr>
			<th>Date/Time</th>
			<th>Contact Name</th>
			<th>City, State</th>
			<th>Prefered Facility</th>
			<th>Relationship to Seeker</th>
			<th>Assign To</th>
		</tr>
	</thead>
	<tbody>%%NEW_LEADS%%</tbody>
</table>

<table class="new_placements tablesorter">
	<thead>
		<tr>
			<th>Date/Time</th>
			<th>Contact Name</th>
			<th>Chosen Facility</th>
			<th>Consultant</th>
			<th>Invoice No.</th>
			<th>Status</th>
		</tr>
	</thead>
	<tbody>%%NEW_PLACEMENTS%%</tbody>
</table>

<table class="calendar_alerts tablesorter">
	<thead>
		<tr>
			<th>Date/Time</th>
			<th>Alert For</th>
			<th>From</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>%%CALENDAR_ALERTS%%</tbody>
</table>

<table class='immediate_leads tablesorter'>
	<thead>
		<tr>
			<th>Date/Time</th>
			<th>Contact Name</th>
			<th>Chosen Facility</th>
			<th>Consultant</th>
			<th>Invoice No.</th>
			<th>Status</th>
		</tr>
	</thead>
	<tbody>
		%%NEW_PLACEMENT%%
	</tbody>
</table>