<div id="<?=routes::getInstance()->getCurrentTopLevelPageID();?>_content_wrapper">
	<div id="header_banner">
		<div class="semi_transparent"></div>
	</div>
	<div id="page_content" class="clearfix">
		<a href = "/" class="back sprite">Back to Home</a>
		<div class="pHxxl pVxl clearfix">
			<ul class="unstyled helvetica77">
				<li><a href="/home">HOME</a></li>
					<ul class="unstyled">
						<li><a href="/account/register">LIST YOUR HOME NOW</a></li>
						<li><a href="/faq">ADVICE ON CHOOSING HOMES</a></li>
						<li><a href="/about">LEARN ABOUT FOR PROCESS</a></li>
					</ul>
				
				<li><a href="/about">ABOUT</a></li>
				
				<li><a href="/faq">FAQ</a></li>
				
				<li><a href="/contact_us">CONTACT US</a></li>
					<ul class="unstyled">
						<li><a href="/faq#what-is-assisted-living">What is Assisted Living?</a></li>
						<li><a href="/faq#what-are-residential-care-homes">What are Residential Care Homes?</a></li>
						<li><a href="/faq#what-are-home-care-providers">What are Home Care Providers?</a></li>
					</ul>
					
				<li><a href="/">HCP Account</a>
					<ul class="unstyled">
						<li><a href="/account/login">Sign In</a></li>
						<li><a href="/account/register">Register</a></li>
					</ul>
				</li>
				
				<li><a href="/about">About</a></li>
				<li><a href="/contact_us">Contact Us</a></li>
				<li><a href="/account/register">List Your Property</a></li>
				<li><a href="/faq">FAQ</a></li>
				<li><a href="/privacy_policy">Privacy Policy</a></li>
				<li><a href="/term_of_use">Term of Use</a></li>
			</ul>
		
		</div>
	</div>
</div>