<div id="login_content_wrapper">

	<div id="header_banner">
		<div class="semi_transparent"></div>
	</div>
	
	<div id="page_content" class="clearfix">
		<a class="back sprite mBxl" href="/"></a>
		<h1 class="pTl helvetica77"><span class="fcBlue">Sign-in</span> to your Health Care Provider Account</h1>
		<span class="gotham_bold fs-m">Don't have an account? <a class="fs-m underline" href="/account/register">Register here.</a></span>
			
		<div class="clearfix mTl">
			<div id="form_container" class="fleft mBl pVm pHl">
				<form method="post" action="/account/login">
					<label>Email<br><input type="text" name="email" <?=$this->_get('login_error') ? 'class="invalid"' : ''?>><?=$this->_get('login_error') ? '<span class="loginError sprite">Wrong username and/or password.</span>' : ''?></label><br>
					<label>Password<br><input type="password" name="password" <?=$this->_get('login_error') ? 'class="invalid"' : ''?>></label><br>
					<div><input type="checkbox" name="remember"><span class="mLxs fs-10">Remember me</span></div>
					<div class="mTxxl gotham_bold">Forgot your password? <a class="underline" href="/account/forgot_password">Click here.</a></div><br>
					<input class="mTxxl mLxxl" type="submit" name="login" value=" ">
				</form>
			</div>
			
			<div class="fright align_j">
				<h3 class="fcBlue mTs">Why does Looking for ElderCare<sup class="fs-xxs">TM</sup> stand out?</h3>
				<p class="fs-s mTs mB">Health Care Providers find it more efficient to find potential seekers through Looking for ElderCare<sup class="fs-xxs">TM</sup>'s system.</p>
				<!-- <a class="fright gotham_book" href="">Learn more...</a> -->
			</div>
			
		</div>
			
		<div class="mBm"><a  class="back sprite" href="/"></a></div>
	</div>

</div>